version: "3"
services:
  shop:
    image: kate-distsys/app
    ports:
      - "8080:8080"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      KATE_AUTH_BASEURL: http://auth:8080/
      SPRING_PROFILES_ACTIVE: shop
      DB_HOST: db
      MQ_HOST: mq
    depends_on:
      - db
      - mq

  email:
    image: kate-distsys/app
    environment:
      KATE_EMAIL_FROM: Test Shop <kate-tmp@ldvsoft.net>
      SPRING_PROFILES_ACTIVE: email
      SPRING_MAIL_HOST: mail.ldvsoft.net
      SPRING_MAIL_USERNAME: kate-tmp
      SPRING_MAIL_PASSWORD: password
      SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL: smtp
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_PORT: 25
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
      DB_HOST: db
      MQ_HOST: mq
    depends_on:
      - db
      - mq

  auth:
    image: kate-distsys/app
    ports:
      - "8081:8080"
    environment:
      KATE_AUTH_BASEURL: http://localhost:8081/
      SPRING_PROFILES_ACTIVE: auth
      DB_HOST: db
      MQ_HOST: mq
    depends_on:
      - db
      - mq

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  mq:
    image: webcenter/activemq:5.14.3
